//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFAMailRequest
    {
        public int MFAMailRequestId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string RequestCode { get; set; }
        public int UserId { get; set; }
    }
}
