//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class timetrackerDBEntities : DbContext
    {
        public timetrackerDBEntities()
            : base("name=timetrackerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<DaysForUse> DaysForUse { get; set; }
        public virtual DbSet<DaysUser> DaysUser { get; set; }
        public virtual DbSet<GCToken> GCToken { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<MFAMailRequest> MFAMailRequest { get; set; }
        public virtual DbSet<Module> Module { get; set; }
        public virtual DbSet<Office> Office { get; set; }
        public virtual DbSet<Pages> Pages { get; set; }
        public virtual DbSet<PageType> PageType { get; set; }
        public virtual DbSet<Privilege> Privilege { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectManager> ProjectManager { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<RolesPrivileges> RolesPrivileges { get; set; }
        public virtual DbSet<RolesUsers> RolesUsers { get; set; }
        public virtual DbSet<TimeHours> TimeHours { get; set; }
        public virtual DbSet<UsersProject> UsersProject { get; set; }
        public virtual DbSet<Privilege_User> Privilege_User { get; set; }
        public virtual DbSet<temppagetype> temppagetype { get; set; }
        public virtual DbSet<view_menu> view_menu { get; set; }
        public virtual DbSet<viewPMUser> viewPMUser { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<view_DaysUserStatus> view_DaysUserStatus { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
