//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesPrivileges
    {
        public int RolePrivId { get; set; }
        public int RoleId { get; set; }
        public string PrivilegeId { get; set; }
    
        public virtual Privilege Privilege { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
