//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_DaysUserStatus
    {
        public System.DateTime THDate { get; set; }
        public int UserId { get; set; }
        public string DayStatus { get; set; }
        public Nullable<System.DateTime> DayDate { get; set; }
        public string DayObservations { get; set; }
        public Nullable<decimal> quantity { get; set; }
    }
}
