name: Build and deploy ASP app to Azure Web App - sxtimetracker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022     # 👈 fijamos imagen
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      # 🔐 SOLO si usas DevExpress por NuGet. Crea el secreto DEVEXPRESS_NUGET con tu URL /api
      - name: Add DevExpress NuGet feed
        if: ${{ secrets.DEVEXPRESS_NUGET != '' }}
        shell: pwsh
        run: |
          nuget sources Remove -Name DevExpress -NonInteractive | Out-Null
          nuget sources Add -Name DevExpress -Source "${{ secrets.DEVEXPRESS_NUGET }}" -NonInteractive
          nuget sources List

      - name: Restore NuGet packages (solution)
        run: nuget restore .\Systems-X-Time-Tracker.sln -NonInteractive

      - name: Build solution (Release)
        run: msbuild .\Systems-X-Time-Tracker.sln /m /p:Configuration=Release /p:Platform="Any CPU" /p:RestorePackages=false

      - name: Publish to folder (explicit csproj + SolutionDir)
        shell: pwsh
        run: |
          $pub = "$env:GITHUB_WORKSPACE\published"
          New-Item -ItemType Directory -Path $pub -Force | Out-Null
          msbuild .\Systems-X-Time-Tracker\Systems-X-Time-Tracker\TimeTracker.csproj `
            /t:Build;PipelinePreDeployCopyAllFilesToOneFolder `
            /p:_PackageTempDir="$pub" `
            /p:Configuration=Release `
            /p:SolutionDir="$env:GITHUB_WORKSPACE\"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: published/**

  deploy:
    runs-on: windows-2022
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_86B240BEAAF24C3588F28C0E140FC740 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C27500F18322475EBFE1D62DA6534F34 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B777F1B32C31410BAC5AD478E5BCF322 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sxtimetracker'
          slot-name: 'Production'
          package: .

