//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int LogId { get; set; }
        public string LogName { get; set; }
        public string LogTable { get; set; }
        public string LogAction { get; set; }
        public System.DateTime LogDate { get; set; }
        public Nullable<int> LogUserId { get; set; }
        public string LogIpAddress { get; set; }
        public string LogData1 { get; set; }
        public string LogData2 { get; set; }
        public string LogData3 { get; set; }
    }
}
