//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pages
    {
        public int PageId { get; set; }
        public string PageIdAccess { get; set; }
        public string PageUrl { get; set; }
        public string PageTitle { get; set; }
        public string PageShortDesc { get; set; }
        public string PageLongDesc { get; set; }
        public string PageHelpUrl { get; set; }
        public int AreaId { get; set; }
        public int ModuleId { get; set; }
        public int PageTypeId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Visible { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUser { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Module Module { get; set; }
        public virtual PageType PageType { get; set; }
    }
}
