//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeHours
    {
        public int TimeHoursId { get; set; }
        public System.DateTime THDate { get; set; }
        public string THFrom { get; set; }
        public string THTo { get; set; }
        public decimal Duration { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public int UserId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public string ActDescription { get; set; }
        public Nullable<bool> Exported { get; set; }
        public bool Billable { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string DayStatus { get; set; }
        public Nullable<bool> DayApproved { get; set; }
        public string InternalNote { get; set; }
        public string TaskAllocation { get; set; }
        public Nullable<bool> Visible { get; set; }
        public string ApprovalNote { get; set; }
        public Nullable<decimal> THours { get; set; }
        public string GCalendarId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Project Project { get; set; }
        public virtual Users Users { get; set; }
    }
}
