//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_menu
    {
        public long id { get; set; }
        public string PageIdAccess { get; set; }
        public string AreaShortDesc { get; set; }
        public string AreaLongDesc { get; set; }
        public string AreaTitle { get; set; }
        public string AreaIconUrl { get; set; }
        public Nullable<int> AreaOrder { get; set; }
        public string PageShortDesc { get; set; }
        public string PageLongDesc { get; set; }
        public int AreaId { get; set; }
        public int ModuleId { get; set; }
        public int PageId { get; set; }
        public string ModuleShortDesc { get; set; }
        public string ModuleTitle { get; set; }
        public string ModuleIconUrl { get; set; }
        public Nullable<int> ModuleOrder { get; set; }
        public int PageTypeId { get; set; }
        public string PageTypeTitle { get; set; }
        public string PageTypeIconUrl { get; set; }
        public string PageTitle { get; set; }
        public string PageUrl { get; set; }
    }
}
