//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewPMUser
    {
        public int UserId { get; set; }
        public int CompanyId { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordCry { get; set; }
        public string SecurityStamp { get; set; }
        public Nullable<System.DateTime> LockoutEndDate { get; set; }
        public string LockoutEnable { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool Active { get; set; }
        public bool IsSuperUser { get; set; }
        public Nullable<int> exits { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public byte[] ProfilePict { get; set; }
        public System.DateTime FactorEndDate { get; set; }
    }
}
